### ISSUE TITLE
Can not login with existing yunohost users

### ISSUE THREAD

**Issue by ozbek** [YunoHost-Apps/weblate_ynh#9]
Apparently, user connection (LDAP integration) is not working. I can not login with the existing user credentials. Do I need to perform additional steps?

Using YunoHost 2.7.10 (stable) on Rasperry PI.

**Comment by Jibec** [comment]
Thank you for your report, yes this wasn't enable on purpose.

If I do this, I'm afraid it will force every translation contributor to have an LDAP account, which means two things:
. manual administration work for the server owner
. giving email address and other services to contributors

As Weblate is aim to welcome contributors from any languages, it may be dozens or hundreds.
So, I'm not sure this feature should be enable, that's why I enabled by default connection from github, Fedora and Ubuntu, so it lower the number of user creation.

Another solution is to make yunohost openid ready. I started working on the 'simpleopenid' app, but as I'm not seeing this as an issue, I stopped.

What do you think of this?

**Comment by ozbek** [comment]
That sounds reasonable, thanks for the detailed explanation.

I will just use separate registration for weblate. Thanks again.
